set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

if(DEFINED ENV{TOOLCHAIN_ROOT_PATH})
    file(TO_CMAKE_PATH $ENV{TOOLCHAIN_ROOT_PATH} TOOLCHAIN_ROOT_PATH)
else()
    message(FATAL_ERROR "TOOLCHAIN_ROOT_PATH env must be defined")
endif()

set(TOOLCHAIN_ROOT_PATH ${TOOLCHAIN_ROOT_PATH} CACHE STRING "root path to toolchain")
set(CMAKE_RC_COMPILER "${TOOLCHAIN_ROOT_PATH}/toolchains/toolchains/gcc-mingw-msvcrt-x86_64/bin/x86_64-w64-mingw32-windres")
set(CMAKE_C_COMPILER "${TOOLCHAIN_ROOT_PATH}/toolchains/toolchains/gcc-mingw-msvcrt-x86_64/bin/x86_64-w64-mingw32-gcc")
set(CMAKE_CXX_COMPILER "${TOOLCHAIN_ROOT_PATH}/toolchains/toolchains/gcc-mingw-msvcrt-x86_64/bin/x86_64-w64-mingw32-g++")

set(CMAKE_FIND_FRAMEWORK FIRST)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)