name: release-mingw64
on:
  push:
    tags:
      - 'mingw64-*'

permissions:
  contents: write

env:
  MINGW_VERSION: "20240109"

jobs:
  setup:
    runs-on: ubuntu-20.04
    outputs:
      VERSION: ${{ steps.get_version.outputs.VERSION }}
    steps:
      - uses: actions/checkout@v4
      - name: get-version
        id: get_version
        run: echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT
      - name: init toolchains
        run: |
          sudo apt install -y flex bison m4 texinfo bzip2
      - name: build mingw-i686
        run: |
          sh mingw64/build-i686.sh
      - name: package mingw-i686
        run: |
          cd mingw64/mingw-ubuntu-i686/i686/
          tar -zcf ${{ env.MINGW_VERSION }}.i686.tar.gz bin i686-w64-mingw32 include lib libexec share

      - name: build mingw-x86_64
        run: |
          sh mingw64/build-x86_64.sh
      - name: package mingw-x86_64
        run: |
          cd mingw64/mingw-ubuntu-x86_64/x86_64/
          tar -zcf ${{ env.MINGW_VERSION }}.x86_64.tar.gz bin x86_64-w64-mingw32 include lib libexec share

      - name: create-release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ needs.setup.outputs.VERSION }}
          name: Release ${{ needs.setup.outputs.VERSION }}
          files: |
            mingw64/mingw-ubuntu-i686/i686/${{ env.MINGW_VERSION }}.i686.tar.gz
            mingw64/mingw-ubuntu-x86_64/x86_64/${{ env.MINGW_VERSION }}.x86_64.tar.gz
